/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonArray
import com.google.gson.JsonObject

class AllocationProfile(json: JsonObject) : Response(json) {

    /**
     * 上次累加器重置的时间戳。
     *
     * 如果累加器尚未重置，则此字段不存在。
     *
     * 可以返回 <code>null</code>。
     */
    fun getDateLastAccumulatorReset(): Int {
        return getAsInt("dateLastAccumulatorReset")
    }

    /**
     * 上次手动触发 GC 的时间戳。
     *
     * 如果 GC 尚未手动触发，则此字段不存在。
     *
     * 可以返回 <code>null</code>。
     */
    fun getDateLastServiceGC(): Int {
        return getAsInt("dateLastServiceGC")
    }

    /**
     * 所有类类型的分配信息。
     */
    fun getMembers(): ElementList<ClassHeapStats> {
        return object : ElementList<ClassHeapStats>(json.get("members").asJsonArray) {
            override fun basicGet(array: JsonArray, index: Int): ClassHeapStats {
                return ClassHeapStats(array.get(index).asJsonObject)
            }
        }
    }

    /**
     * 关于 isolate 的内存使用信息。
     */
    fun getMemoryUsage(): MemoryUsage {
        return MemoryUsage(json.get("memoryUsage").asJsonObject)
    }
}
