/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonPrimitive

/**
 * {@link BoundField} 表示绑定到 {@link Instance} 中特定值的字段。
 */
class BoundField(json: JsonObject) : Element(json) {

    /**
     * @return <code>String</code> 或 <code>int</code> 之一
     */
    fun getName(): Any? {
        val elem = json.get("name")
        if (elem != null && elem.isJsonPrimitive) {
            val p = elem as JsonPrimitive
            if (p.isString) return p.asString
            if (p.isNumber) return p.asInt
        }
        return null
    }

    /**
     * @return <code>InstanceRef</code> 或 <code>Sentinel</code> 之一
     */
    fun getValue(): InstanceRef? {
        val elem = json.get("value")
        if (elem == null || !elem.isJsonObject) {
            return null
        }
        val child = elem.asJsonObject
        val type = child.get("type").asString
        if ("Sentinel" == type) {
            return null
        }
        return InstanceRef(child)
    }
}
