/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

class ClassHeapStats(json: JsonObject) : Response(json) {

    /**
     * 自上次重置累加器以来为类实例分配的字节数。
     */
    fun getAccumulatedSize(): Int {
        return getAsInt("accumulatedSize")
    }

    /**
     * 当前为类实例分配的字节数。
     */
    fun getBytesCurrent(): Int {
        return getAsInt("bytesCurrent")
    }

    /**
     * 与此内存信息关联的类。
     */
    fun getClassRef(): ClassRef {
        return ClassRef(json.get("class").asJsonObject)
    }

    /**
     * 自上次重置累加器以来分配的类实例数。
     */
    fun getInstancesAccumulated(): Int {
        return getAsInt("instancesAccumulated")
    }

    /**
     * 当前存活的类实例数。
     */
    fun getInstancesCurrent(): Int {
        return getAsInt("instancesCurrent")
    }
}
