/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonArray
import com.google.gson.JsonObject

/**
 * {@link Context} 是一个数据结构，用于保存某些闭包的捕获变量。
 */
class Context(json: JsonObject) : Obj(json) {

    /**
     * 包含此上下文对象的函数的名称。
     */
    fun getName(): String {
        return getAsString("name")!!
    }

    /**
     * 此上下文的封闭上下文。
     *
     * 可以返回 <code>null</code>。
     */
    fun getParent(): ContextRef? {
        val obj = json.get("parent")?.asJsonObject ?: return null
        val type = json.get("type")?.asString ?: return ContextRef(obj)
        if ("Instance" == type || "@Instance" == type) {
            val kind = json.get("kind")?.asString ?: return ContextRef(obj)
            if ("Null" == kind) return null
        }
        return ContextRef(obj)
    }

    /**
     * 此上下文对象中的变量。
     */
    fun getVariables(): ElementList<ContextElement> {
        return object : ElementList<ContextElement>(json.get("variables").asJsonArray) {
            override fun basicGet(array: JsonArray, index: Int): ContextElement {
                return ContextElement(array.get(index).asJsonObject)
            }
        }
    }
}
