/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * {@link ErrorRef} 是对 {@link ErrorObj} 的引用。
 */
class ErrorRef(json: JsonObject) : ObjRef(json) {

    /**
     * 这是什么类型的错误？
     */
    fun getKind(): ErrorKind {
        val value = json.get("kind")
        try {
            return if (value == null) ErrorKind.Unknown else ErrorKind.valueOf(value.asString)
        } catch (e: IllegalArgumentException) {
            return ErrorKind.Unknown
        }
    }

    /**
     * 发生的错误的描述。
     */
    fun getMessage(): String {
        return getAsString("message")!!
    }
}
