/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonArray
import com.google.gson.JsonObject

/**
 * {@link FlagList} 表示完整的 VM 命令行标志集。
 */
class FlagList(json: JsonObject) : Response(json) {

    /**
     * VM 中所有标志的列表。
     */
    fun getFlags(): ElementList<Flag> {
        return object : ElementList<Flag>(json.get("flags").asJsonArray) {
            override fun basicGet(array: JsonArray, index: Int): Flag {
                return Flag(array.get(index).asJsonObject)
            }
        }
    }
}
