/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * {@link IsolateGroupRef} is a reference to an {@link IsolateGroup} object.
 */
class IsolateGroupRef(json: JsonObject) : Response(json) {

    /**
     * The id which is passed to the getIsolateGroup RPC to load this isolate group.
     */
    fun getId(): String? {
        return getAsString("id")
    }

    /**
     * Specifies whether the isolate group was spawned by the VM or embedder for internal use. If
     * `false`, this isolate group is likely running user code.
     */
    fun getIsSystemIsolateGroup(): Boolean {
        return getAsBoolean("isSystemIsolateGroup")
    }

    /**
     * A name identifying this isolate group. Not guaranteed to be unique.
     */
    fun getName(): String? {
        return getAsString("name")
    }

    /**
     * A numeric id for this isolate group, represented as a string. Unique.
     */
    fun getNumber(): String? {
        return getAsString("number")
    }
}
