/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * {@link IsolateRef} 是对 {@link Isolate} 对象的引用。
 */
class IsolateRef(json: JsonObject) : Response(json) {

    /**
     * 传递给 getIsolate RPC 以加载此 isolate 的 ID。
     */
    fun getId(): String? {
        return getAsString("id")
    }

    /**
     * 指定 isolate 是否由 VM 或嵌入器为内部使用而生成。如果为 `false`，
     * 则此 isolate 可能正在运行用户代码。
     */
    fun getIsSystemIsolate(): Boolean {
        return getAsBoolean("isSystemIsolate")
    }

    /**
     * 此 isolate 所属的 isolate 组的 ID。
     */
    fun getIsolateGroupId(): String? {
        return getAsString("isolateGroupId")
    }

    /**
     * 标识此 isolate 的名称。不保证唯一。
     */
    fun getName(): String? {
        return getAsString("name")
    }

    /**
     * 此 isolate 的数字 ID，表示为字符串。唯一。
     */
    fun getNumber(): String? {
        return getAsString("number")
    }
}
