/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * {@link LibraryDependency} 提供有关导入或导出的信息。
 */
class LibraryDependency(json: JsonObject) : Element(json) {

    /**
     * 从此依赖项中隐藏的符号列表。
     *
     * 可以返回 <code>null</code>。
     */
    fun getHides(): List<String>? {
        return if (json.get("hides") == null) null else getListString("hides")
    }

    /**
     * 此依赖项是否被延迟加载？
     */
    fun getIsDeferred(): Boolean {
        return getAsBoolean("isDeferred")
    }

    /**
     * 此依赖项是导入（而不是导出）吗？
     */
    fun getIsImport(): Boolean {
        return getAsBoolean("isImport")
    }

    /**
     * 'as' 导入的前缀，或 null。
     */
    fun getPrefix(): String? {
        return getAsString("prefix")
    }

    /**
     * 从此依赖项中可见的符号列表。
     *
     * 可以返回 <code>null</code>。
     */
    fun getShows(): List<String>? {
        return if (json.get("shows") == null) null else getListString("shows")
    }

    /**
     * 被导入或导出的库。
     */
    fun getTarget(): LibraryRef {
        return LibraryRef(json.get("target").asJsonObject)
    }
}
