/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * {@link ObjRef} 是对 {@link Obj} 的引用。
 */
open class ObjRef(json: JsonObject) : Response(json) {

    /**
     * 如果对象的 ID 是固定的，则提供并设置为 true。如果为 true，则对象的 ID
     * 保证不会更改或过期。但是，对象仍可能被 _Collected_。
     *
     * 可以返回 <code>null</code>。
     */
    fun getFixedId(): Boolean? {
        return getAsBoolean("fixedId")
    }

    /**
     * 对象的唯一标识符。传递给 getObject RPC 以加载此对象。
     */
    fun getId(): String {
        return getAsString("id") ?: ""
    }

    open fun getName(): String {
        return getAsString("name") ?: ""
    }

    fun getLibrary(): LibraryRef? {
        val obj = json.get("library")?.asJsonObject ?: return null
        return LibraryRef(obj)
    }


}
