/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonArray
import com.google.gson.JsonObject

class ProcessMemoryItem(json: JsonObject) : Element(json) {

    /**
     * 此内存桶的细分。
     */
    fun getChildren(): ElementList<ProcessMemoryItem> {
        return object : ElementList<ProcessMemoryItem>(json.get("children").asJsonArray) {
            override fun basicGet(array: JsonArray, index: Int): ProcessMemoryItem {
                return ProcessMemoryItem(array.get(index).asJsonObject)
            }
        }
    }

    /**
     * 此项目的较长描述。
     */
    fun getDescription(): String? {
        return getAsString("description")
    }

    /**
     * 此内存桶的短名称。
     */
    fun getName(): String? {
        return getAsString("name")
    }

    /**
     * 内存大小（以字节为单位）。这是一个保留大小，而不是浅层大小。也就是说，它
     * 包括子项的大小。
     */
    fun getSize(): Int {
        return getAsInt("size")
    }
}
