/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * 请参见 getSupportedProtocols。
 */
class Protocol(json: JsonObject) : Element(json) {

    /**
     * 协议的主要修订版本。
     */
    fun getMajor(): Int {
        return getAsInt("major")
    }

    /**
     * 协议的次要修订版本。
     */
    fun getMinor(): Int {
        return getAsInt("minor")
    }

    /**
     * 受支持的协议名称。
     */
    fun getProtocolName(): String? {
        return getAsString("protocolName")
    }
}
