/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonArray
import com.google.gson.JsonObject

/**
 * {@link ProtocolList} 包含服务实例支持的所有协议的列表。
 */
class ProtocolList(json: JsonObject) : Response(json) {

    /**
     * 此服务提供的受支持协议列表。
     */
    fun getProtocols(): ElementList<Protocol> {
        return object : ElementList<Protocol>(json.get("protocols").asJsonArray) {
            override fun basicGet(array: JsonArray, index: Int): Protocol {
                return Protocol(array.get(index).asJsonObject)
            }
        }
    }
}
