/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonArray
import com.google.gson.JsonObject

/**
 * 请参见 getRetainingPath。
 */
class RetainingPath(json: JsonObject) : Response(json) {

    /**
     * 构成保留路径的对象链。
     */
    fun getElements(): ElementList<RetainingObject> {
        return object : ElementList<RetainingObject>(json.get("elements").asJsonArray) {
            override fun basicGet(array: JsonArray, index: Int): RetainingObject {
                return RetainingObject(array.get(index).asJsonObject)
            }
        }
    }

    /**
     * 保存对指定对象的引用的 GC 根类型。可能的值
     * 包括：* 类表 * 本地句柄 * 持久句柄 * 堆栈 * 用户全局 * 弱
     * 持久句柄 * 未知
     */
    fun getGcRootType(): String? {
        return getAsString("gcRootType")
    }

    /**
     * 保留路径的长度。
     */
    fun getLength(): Int {
        return getAsInt("length")
    }
}
