/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * {@link Script} 提供有关 Dart 语言脚本的信息。
 */
class Script(json: JsonObject) : Obj(json) {

    /**
     * 可以返回 <code>null</code>。
     */
    fun getColumnOffset(): Int {
        return getAsInt("columnOffset")
    }

    /**
     * 拥有此脚本的库。
     */
    fun getLibrary(): LibraryRef {
        return LibraryRef(json.get("library").asJsonObject)
    }

    /**
     * 可以返回 <code>null</code>。
     */
    fun getLineOffset(): Int {
        return getAsInt("lineOffset")
    }

    /**
     * 此脚本的源代码。对于某些内置脚本，这可以为 null。
     *
     * 可以返回 <code>null</code>。
     */
    fun getSource(): String? {
        return getAsString("source")
    }

    /**
     * 一个表，用于编码从标记位置到行和列的映射。如果
     * 源代码不可用，则此字段为 null。
     *
     * 可以返回 <code>null</code>。
     */
    fun getTokenPosTable(): List<List<Int>>? {
        return getListListInt("tokenPosTable")
    }

    /**
     * 加载此脚本的 uri。
     */
    fun getUri(): String? {
        return getAsString("uri")
    }
}
