/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * {@link SourceLocation} 类用于指定某个脚本中的位置或范围。
 */
class SourceLocation(json: JsonObject) : Response(json) {

    /**
     * 与此位置关联的列。仅对非合成标记位置提供。
     *
     * 可以返回 <code>null</code>。
     */
    fun getColumn(): Int {
        return getAsInt("column")
    }

    /**
     * 如果这是范围，则为位置的最后一个标记。
     *
     * 可以返回 <code>null</code>。
     */
    fun getEndTokenPos(): Int {
        return getAsInt("endTokenPos")
    }

    /**
     * 与此位置关联的行。仅对非合成标记位置提供。
     *
     * 可以返回 <code>null</code>。
     */
    fun getLine(): Int {
        return getAsInt("line")
    }

    /**
     * 包含源位置的脚本。
     */
    fun getScript(): ScriptRef {
        return ScriptRef(json.get("script").asJsonObject)
    }

    /**
     * 位置的第一个标记。
     */
    fun getTokenPos(): Int {
        return getAsInt("tokenPos")
    }
}
