/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * {@link SourceReportCoverage} 类表示一个
 * SourceReportRange 的覆盖信息。
 */
class SourceReportCoverage(json: JsonObject) : Element(json) {

    /**
     * SourceReportRange 中已执行的标记位置（如果启用了 reportLines，则为行号）列表。
     * 列表已排序。
     */
    fun getHits(): List<Int> {
        return getListInt("hits")
    }

    /**
     * SourceReportRange 中未执行的标记位置（如果启用了 reportLines，则为行号）列表。
     * 列表已排序。
     */
    fun getMisses(): List<Int> {
        return getListInt("misses")
    }
}
