/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonArray
import com.google.gson.JsonObject

class Timeline(json: JsonObject) : Response(json) {

    /**
     * 时间线覆盖的时间段。
     */
    fun getTimeExtentMicros(): Int {
        return getAsInt("timeExtentMicros")
    }

    /**
     * 收集 traceEvents 的时间段的开始。
     */
    fun getTimeOriginMicros(): Int {
        return getAsInt("timeOriginMicros")
    }

    /**
     * 时间线事件列表。这些事件不保证顺序；特别是，这些
     * 事件相对于它们的时间戳可能是无序的。
     */
    fun getTraceEvents(): ElementList<TimelineEvent> {
        return object : ElementList<TimelineEvent>(json.get("traceEvents").asJsonArray) {
            override fun basicGet(array: JsonArray, index: Int): TimelineEvent {
                return TimelineEvent(array.get(index).asJsonObject)
            }
        }
    }
}
