/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

class TimelineFlags(json: JsonObject) : Response(json) {

    /**
     * 所有可用时间线流的列表。
     */
    fun getAvailableStreams(): List<String> {
        return getListString("availableStreams")
    }

    /**
     * 当前启用的时间线流列表。
     */
    fun getRecordedStreams(): List<String> {
        return getListString("recordedStreams")
    }

    /**
     * 当前使用的记录器名称。记录器类型包括但不限于：
     * Callback, Endless, Fuchsia, Macos, Ring, Startup, 和 Systrace。如果当前没有设置记录器，
     * 则设置为 "null"。
     */
    fun getRecorderName(): String? {
        return getAsString("recorderName")
    }
}
