/*
 * Copyright (c) 2015, the Dart project authors.
 *
 * Licensed under the Eclipse Public License v1.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package vm.element

// This file is generated by the script: pkg/vm_service/tool/generate.dart in dart-lang/sdk.

import com.google.gson.JsonObject

/**
 * A {@link TypeParameters} object represents the type argument vector for some uninstantiated
 * generic type.
 */
class TypeParameters(json: JsonObject) : Element(json) {

    /**
     * The bounds set on each type parameter.
     */
    fun getBounds(): TypeArgumentsRef {
        return TypeArgumentsRef(json.get("bounds").asJsonObject)
    }

    /**
     * The default types for each type parameter.
     */
    fun getDefaults(): TypeArgumentsRef {
        return TypeArgumentsRef(json.get("defaults").asJsonObject)
    }

    /**
     * The names of the type parameters.
     */
    fun getNames(): List<String> {
        return getListString("names")
    }
}
